tasks:
#  - command: pip3 install -U platformio && platformio run -e d1_mini
  - init: pip3 install -U platformio
  - command: pio run

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
