tasks:
  - command: pip3 install -U platformio && platformio run -e d1_mini
  - command: apt install -y sftp

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
