name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: "recursive"
      - name: Install deps
        run: |
          #apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: |
          pio run
          mv .pio/build/d1_mini/firmware.bin docs/firmware.bin
